name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./orderservice/pom.xml
          mvn clean package -f ./deliveryservice/pom.xml
          mvn clean package -f ./inventoryservice/pom.xml

      - name: Docker Build and push for Orderservice
        uses: docker/build-push-action@v4
        with:
          context: ./orderservice
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/orderservice:latest
            ghcr.io/${{ github.repository }}/orderservice:${{ github.ref_name }}
            
      - name: Docker Build and push for Deliveryservice
        uses: docker/build-push-action@v4
        with:
          context: ./deliveryservice
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/deliveryservice:latest
            ghcr.io/${{ github.repository }}/deliveryservice:${{ github.ref_name }}
            
      - name: Docker Build and push for Inventoryservice
        uses: docker/build-push-action@v4
        with:
          context: ./inventoryservice
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/inventoryservice:latest
            ghcr.io/${{ github.repository }}/inventoryservice:${{ github.ref_name }}
            
