server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: orderservice
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**, 
        - id: deliveryservice
          uri: http://localhost:8083
          predicates:
            - Path=/deliveries/**, 
        - id: inventoryservice
          uri: http://localhost:8084
          predicates:
            - Path=/inventories/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: orderservice
          uri: http://orderservice:8080
          predicates:
            - Path=/orders/**, 
        - id: deliveryservice
          uri: http://deliveryservice:8080
          predicates:
            - Path=/deliveries/**, 
        - id: inventoryservice
          uri: http://inventoryservice:8080
          predicates:
            - Path=/inventories/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
